name: 'Git config user'
description: 'Set git user name and email address'
inputs:
  name:
    description: 'git config user.name'
    required: false
    default: github-actions[bot]
  email:
    description: 'git config user.email'
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
runs:
  using: "composite"
  steps:
    - name: git config user
      run: |
        git config user.name $NAME
        git config user.email $EMAIL
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        EMAIL: ${{ inputs.email }}
branding:
  icon: 'github'  
  color: 'black'
