name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-default-user:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: test "$(git config user.name)" = "github-actions[bot]"
      - run: test "$(git config user.email)" = "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Test committable
        run: |
          echo "test" > test
          git add .
          git commit -m "test"

  test-specified-user:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019, macos-11, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          name: SnowCait
          email: SnowCait@example.com
      - run: test "$(git config user.name)" = "SnowCait"
      - run: test "$(git config user.email)" = "SnowCait@example.com"
      - name: Test committable
        run: |
          echo "test" > test
          git add .
          git commit -m "test"
  test-passing:
    needs: [ test-default-user, test-specified-user ]
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - run: echo "All tests have passed."
